### ISSUE TITLE
Review applicability of eclipse new access rules for next release

### ISSUE THREAD

**Issue by derheld42** [bndtools/bndtools#1005]
Determine if eclipse.newaccessrules=true is a setting worthy of being the new default setting for bndtools.

**Comment by bjhargrave** [comment]
@derheld42, @pkriens raised some issues with the access rule changes and I also have some. I will cover them all intermixed below.

----

One of the changes is that `version=latest` and `version=snapshot` now refer to jar files instead of eclipse projects. This would seem to provide better fidelity with the offline build, but access rules seem to now be entirely lost. Was that your intention?

Using `bndtools.builder` as the example. It has the following in its `-buildpath`:

![buildpath1](https://cloud.githubusercontent.com/assets/277682/5980792/f6c9a0a2-a881-11e4-980a-31cc4a0c8768.jpg)

Using the old access rules, the Eclipse build path for these entries looks like:

![buildpath1-oldrules](https://cloud.githubusercontent.com/assets/277682/5980804/13c50b38-a882-11e4-97bd-4991ba10757f.jpg)

You can see that for the `version=latest` and `version=snapshot` entries, the eclipse build path refers to the project (rather than the jar) and includes access rules (not sure why `Forbidden: **` is in there twice).

Using the new access rules, the Eclipse build path for these entries looks like:

![buildpath1-newrules](https://cloud.githubusercontent.com/assets/277682/5980855/8b13a9f6-a882-11e4-8fb9-e76ce0abc2b8.jpg)

For the `version=latest` and `version=snapshot` entries, the eclipse build path now refers to the generated jars but has no access rules. Even if I change the `bndtools.core` reference to `version=project`

![buildpath2](https://cloud.githubusercontent.com/assets/277682/5980878/c37c6eae-a882-11e4-8cb0-3b74d871f217.jpg)

There are still no access rules for the `bndtools.core` entry:

![buildpath2-newrules](https://cloud.githubusercontent.com/assets/277682/5980885/d6658974-a882-11e4-9256-3b41c6f043e1.jpg)

So it seems that access rules are completely gone now even for `version=project`.

----

@pkriens also has some issues with the sources. With the new access rules for `version=latest` and `version=snapshot` entries using the jar instead of the project, the source is from the generated jar and it thus not editable (as it is a resource in the jar). Perhaps this could be corrected by attaching the project source to the jar entry when the jar comes from a project (instead of a repo). A change like this would make it more useful to developers since they can F3 to some source and then edit it rather than having to manually open it in the proper project.

Related to this was an issue with refactoring that @pkriens observed. Since the new access rules for `version=latest` and `version=snapshot` entries are using the jar instead of the project, a refactor operation in a project did not include the types from a entry like it does with `version=project` making refactoring of a set of project less than useful. Perhaps this may be changed by the above suggestion to use the project's source as the source attachment rather than the source in the jar itself. We would need that change to test.

----

While the new access rules improve fidelity with the offline build (with the missing access rules, they are probably identical), they come at a significant developer experience cost: F3 does not open editable source and refactoring does not include dependencies.

**Comment by derheld42** [comment]
As for removing the specialized access rules, no that was not my original intention. My first attempt (that I ended up reverting shortly after merging it in) set out to adjust the access rules in a couple ways to fix some of the transitive dependency issues. It was working well in my test cases, but it failed when building bnd and bndtools (which seemed important :P). While trying to understand what was going on, I noticed that eclipse didn't seem to work deterministically having 2 classpath entries for the same project, one with transitive=true and one with transitive=false. I also didn't know what version=project meant, although in hindsight, it should have been obvious. It's possible not knowing version=project might have led me astray -- maybe that implementation was on to something.

So, after reading the post from BJ, I dropped trying to get transitive dependencies to work and realized I didn't need any access rules to mimick how bnd builds things. I left version=project as a newProjectEntry(), version=snapshot/latest/file as newLibraryEntry(). However, as you've also noticed, there are short comings if you don't use newProjectEntry() (project reference).

So.. I just tried playing with source attachments and I didn't have any success. I can only imagine that refactoring wouldn't work either.

I'm going to use newProjectEntry() for everything but version=file or version=#. Which is basically the old rules.. but I'm going to try without transitive dependencies turned on.

**Comment by derheld42** [comment]
oh yeah. the newLibraryEntry() allows a project to see exactly what's in the .jar file (since it's a reference to the .jar file). If you don't use that, then the problem from e.g. #310 isn't addressed.

I wonder if newLibraryEntry() can be adjusted to use the .jar as the source the reference instead of the /bin/ folder. Investigating...

**Comment by derheld42** [comment]
I think I handled the source attachment and the refactor issues. These worked in my couple tests. And bnd and bndtools built. And all of the test cases relating to transitive dependencies worked too.

Try the #1011 fix and let me know if you notice anything.

It seems like the "real" fix that doesn't feel like a kludge would need to get into the eclipse code base and adjust something. Not sure I'm up for that quite yet. heh.

**Comment by fhuberts** [comment]
Guys,
It would have been better if this had been tried out on a branch.
This is a very difficult issue to fix and is bound to break stuff one or more times.
You're now disturbing people that track the latest builds.
I thought master was supposed to only have new features that are complete.
If not, then please tell me.

**Comment by derheld42** [comment]
It seemed sufficient to have an opt-in flag since i wanted more bake time (user feedback) for this change.
If it's actually affecting anything let me know and I'll change how I'm going about it.

**Comment by pkriens** [comment]
I am ok with these changes if you require a specific opt-in. I prefer to do it in the working branch since we will get feedback quickly.

**Comment by bjhargrave** [comment]
@derheld42 Please try my updates (#1016) to make sure they still work for you in your tests. They worked for me in the bnd, bndtools and osgi builds.

**Comment by derheld42** [comment]
All of the test cases I've been playing with worked except #386.
If I clean all projects, then project b fails to build. I can rebuild B and all is fine.
If I add a this to b/bnd.bnd "-dependson: a", then a full clean ends up building fine.

So yes, it looks good to me.

**Comment by bjhargrave** [comment]
I am working on further improvements now based upon discussions with Peter. Stay tuned...

**Comment by derheld42** [comment]
ok.. it's pretty easy to retest, just let me know.

**Comment by bjhargrave** [comment]
@derheld42 I release some more improvements in #1017. Please test it out. Thanks.

**Comment by derheld42** [comment]
Tested. Looks good.
