### ISSUE TITLE
Exported package not recognized when bundle has embedded jar

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1022]
The [osgi-jax-rs-connector](https://github.com/hstaudacher/osgi-jax-rs-connector) project contains a bundle (jersey-all) that has embedded jars.  That bundle exports the javax.ws api.  My [project](https://github.com/BryanHunt/web-in-a-box) that consumes that bundle fails to build with the error

```The import javax.ws cannot be resolved```

The location of the bndtools repo is: http://hstaudacher.github.io/osgi-jax-rs-connector/index.xml.gz

I have also opened an [issue](https://github.com/hstaudacher/osgi-jax-rs-connector/issues/82) on the osgi-jax-rs-connector, but @hstaudacher says the bundle works with p2 so I'm opening an issue on bndtools.

**Comment by hstaudacher** [comment]
JFYI: I'm using the maven-bundle-plugin to create this jar. You can create it also by your own when executing this pom: https://github.com/hstaudacher/osgi-jax-rs-connector/blob/master/build/com.eclipsesource.jaxrs.jersey.all/pom.xml

**Comment by bjhargrave** [comment]
You cannot compile (with javac) against the embedded jars of a jar. Javac has no idea about Bundle-Classpath so javac only sees the jar listed on the -classpath which is empty of .class files. I think Eclipse (ecj) itself does have support for embedded jars on Bundle-Classpath which is why it is reported to compile ok in Eclipse.

Wrapped jars are fine for runtime but not useful for builds using javac. You should change your build to compile against JAX-RS api jars and use the wrapped jar at runtime.
