### ISSUE TITLE
Builder hangs when launching framework

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1057]
If I make a change, save it, then launch the framework, the launcher gets blocked on building the workspace for some time.  Here is what I see:

![launching_net_springfieldusa_bp_comp_and_bndtools_-_net_springfieldusa_bp_comp_bnd_bnd_-_eclipse_sdk_-__users_bhunt_documents_code_workspaces_buspirate](https://cloud.githubusercontent.com/assets/504299/6512181/92db7cde-c337-11e4-8f69-d6119031d3ba.png)

It will eventually finish building and launch the framework.

**Comment by bjhargrave** [comment]
So what is the bug? Since the launcher needs the thing being built, it needs to wait for it to be built, no?

**Comment by BryanHunt** [comment]
Shouldn’t the code already have been built as soon as I saved the change?  Why does it have to build again when the framework launches?  Also, it gets stuck in building mode for a long time.

**Comment by seanbright** [comment]
Can you quantify "a long time?"

**Comment by bjhargrave** [comment]
Well saving your change triggers the builders. First the source code needs to be compiled and then the bundle built. Building the bundle and trigger downstream bundles to need to rebuild since their -buildpath may reference the bundle you just changed.

My guess is that you have a lot of bundles downstream from the bundle you changed and therefore much work is needed to rebuilt all the bundles dependent on your bundle. 

If you turn on full build logging in the bndtools preference page, you will get log entries in the Eclipse Error Log view showing what work is being done and why.

You should also checkout the latest builds of 3.0 since we have done a major update to the builder.

**Comment by bjhargrave** [comment]
> Why does it have to build again when the framework launches?

I suspect it is still building from your save, not another build cycle because you launched.

**Comment by BryanHunt** [comment]
I am using the latest build of Bndtools.  My workspace contains exactly 3 bundles and each bundle contains exactly one class.  When it gets stuck in the builder, I see the dialog for 10 - 20 seconds.

I understand that saving my change triggers the builder and that is instant.  Why does launching the framework trigger another build?

**Comment by BryanHunt** [comment]
I worked on my code for several hours last night, and I was not able to reproduce the hang.  I'll have another go at it this weekend.

**Comment by bjhargrave** [comment]
@pkriens will look to remove manual building from launcher.

**Comment by pkriens** [comment]
1) I think the delay was caused by downloading a file for the repository
2) I looked at the code and made the build before the launch controlled through a preference
