### ISSUE TITLE
Show files that are being downloaded in the background 

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1161]
When a bnd repository downloads then it would be nice if we saw the status of downloads somewhere  in the GUI

This likely requires an API in bnd so that the repos can report any progress

**Comment by bjhargrave** [comment]
I think this is fixed by https://github.com/bndtools/bndtools/pull/1347

**Comment by gamerson** [comment]
hey @bjhargrave maybe not.  I think what Peter is wanting is a more general solution.  Where even the bundles that bnd builder is downloading as a part of the eclipse build, it would show in a progress view or repo view or elsewhere, so it would show exactly what downloads were happening in the background.  

Right now the only feedback you can get for when downloads start is in the eclipse console "GET STARTED...." etc.  

So, what if we always do the "remote get" in an eclipse job, so it should be easy to see them in the eclipse job/progress view.

I could take a stab at this if I an find some time, but it would not be in 3.2, especially since it requires bnd api changes.

**Comment by pkriens** [comment]
I've used the bnd import aQute.bnd.service.progress.ProgressPlugin.Task in all communications based on the HttpClient. Just need someone to pick it up on the Bndtools side ...

**Comment by gamerson** [comment]
Fixed by https://github.com/bndtools/bndtools/pull/1421
