### ISSUE TITLE
Bundles Using Bundle-ClassPath are not correctly added the the Eclpse build path using the -buildpath instruction

### ISSUE THREAD

**Issue by eli-jordan** [bndtools/bndtools#1198]
If I have a bundle called my.bundle_1.0.0.jar that has a header Bundle-ClassPath: ., A.jar, B.jar
when I add this bundle to my buildpath using -buildpath: my.bundle;version=latest

my.bundle is added to the build path, but A.jar and B.jar are not, and I therefore cannot access any classes in A.jar or B.jar even though they are exported by my.bundle

**Comment by bjhargrave** [comment]
This is a limitation of javac since it knows nothing about OSGi's Bundle-Classpath. A.jar and B.jar are contained inside my.bundle.jar and not on the file system to add to javac's -classpath. Similar issues exist with the eclipse compiler.

bnd must support both building in Eclipse and from the command line (gradle).

**Comment by eli-jordan** [comment]
Wouldn't it be possible to identify that the bundle uses the Bundle-ClassPath header, and extract the relevant entries from the jar, so that they are infact jars in the file system that are accessible to javac

**Comment by bjhargrave** [comment]
Well anything is possible :-) But that would be hard to manage since it is effectively a cache that must track the contents of the actual outer jar. So whenever the outer jar is changed, bnd would need to invalidate the cache and re-cache the inner jars. This same caching would need to be supported in bnd for gradle builds and in bndtools for eclipse compilation (eclipse classpath container). Of course there would be no way for bnd to do anything in a maven build since maven is in control of the compiler classpath.

In general, you should not use Bundle-Classpath unless you are wrapping some 3rd party jar for runtime use. And if you need to compile against the 3rd party jar, you can just put it on your -buildpath. You can use the `packages` attribute to control the package visibility in Eclipse (See <https://github.com/bndtools/bnd/blob/master/biz.aQute.resolve/bnd.bnd#L9> for an example of the `packages` attribute.) if you want some eclipse warnings about using package outside of the specified list.

**Comment by eli-jordan** [comment]
I would also like to note that this does work in PDE. Additionally, these jars are considered by bnd when calculating imports and exports.

**Comment by eli-jordan** [comment]
Ok I see, there are quite a few constains to consider. The maven one seems a bit tricky! 
I'm not sure, but can you use a url on the javac class path? Maybe you could use jar:my.bundle!A.jar

**Comment by bjhargrave** [comment]
> I would also like to note that this does work in PDE. 

That may be true, but we need to support more than just eclipse builds. gradle and maven build fidelity is also very important.

> Additionally, these jars are considered by bnd when calculating imports and exports.

Of course bnd will understand Bundle-Classpath, It is OSGi aware unlike compilers which typically only under understand a flat classpath.

**Comment by eli-jordan** [comment]
*constraints

**Comment by bjhargrave** [comment]
> Ok I see, there are quite a few constains to consider. The maven one seems a bit tricky!
> I'm not sure, but can you use a url on the javac class path? Maybe you could use jar:my.bundle!A.jar

But bnd does not set the compiler path in maven builds. That is set via the poms.

**Comment by eli-jordan** [comment]
Would be foreseeable to add this capability for eclipse and workspace based builds, and generate a warning if maven or a non workspace based grade build is used?

Or would adding a difference in the build for different environments be something you want to avoid?

**Comment by bjhargrave** [comment]
Someone could make a PR for this. I think it will be somewhat complex since it involves changes to bnd (manage cache of inner jars and provide "expanded" buildpath referencing cached inner jars) and possibly bndtools (since it must translate the buildpath into the eclipse classpath container with appropriate source code links).

I don't have time, or the itch, to work on this however.

**Comment by eli-jordan** [comment]
I agree it's not trivial. I may have time in the coming weeks to put together a pull request for this. I think this is a pretty important piece of the osgi spec that is not fully supported by bnd(tools)
