### ISSUE TITLE
new cnf wizard should not offer you a choice of locations

### ISSUE THREAD

**Issue by djencks** [bndtools/bndtools#1200]
starting from scratch the create cnf wizard gives you a choice (usually wrong) of where to put the cnf.  IIUC the only working location is as a peer of the actual projects.  The wizard should figure out where this is and not give you a choice of putting it in an invalid location.

As an example of an invalid location, if the eclipse workspace is off to the side of the git checkout, the wizard wants to put cnf in the eclipse workspace, not where the code is.

**Comment by njbartlett** [comment]
I always run this wizard before creating any bnd projects, so at that point there is no wrong location for the cnf.

However I guess you're saying that, if any bnd projects already exist, then cnf should be placed next to them by default. I can do that. It will be tricky if there are multiple bnd projects in different locations but hopefully that will be very rare.

**Comment by bjhargrave** [comment]
I think the issue is that if you git init a repo in a folder different than your new eclipse workspace folder. Then you create a new bundle project in the git repo folder, at the end of the new bundle project wizard, you are presented with the cnf wizard which suggests creating the cnf folder in the eclipse workspace folder rather in the git repo folder where the just created project exists.

I suspect most people dont run the cnf wizard first (I am not even sure how to do that) and end up in the cnf wizard at the end of the first bundle project wizard.

**Comment by njbartlett** [comment]
Okay so my suggestion should catch that scenario. If there are any bnd projects in the workspace (i.e. having the bndtools project nature) then we use that as the bnd workspace location.
