### ISSUE TITLE
Newly created bundles don't show up in "Available bundles" on Windows

### ISSUE THREAD

**Issue by angelos** [bndtools/bndtools#1206]
When creating new bundles in a project, and then trying to add them to a Run configuration, they pretty persistently don't show up in the .bndrun's "Available bundles". It only seems to happen for the second-and-on bundles.

Reproduction,

- create a new project,
- create a bundle,
- create a run configuration, adding the bundle to the Required Bundles,
- create a second bundle,
- this now doesn't show up in the Available bundles.

Workaround,

- restart Eclipse.

Details,

- Seen on Windows 7, using Eclipse Mars. Highly reproducible.
- Also seen on Mac, but it doesn't seem as persistent.

**Comment by paulbakker** [comment]
Seen it as well on MacOS.

**Comment by pkriens** [comment]
What happens if you close/open the bndrun editor?

**Comment by angelos** [comment]
As in, close the tab that shows the .bndrun configuration? Tried that,
doesn't make a difference.

**Comment by tinustate** [comment]
I just tried the multiple bundles features and though i was doing something wrong. I'm using eclipse mars and additional bundles don't show up in the "available bundles" list. They are correctly generated in the generated directory though, with correct xml and meta data. Glad i saw this bug report. Single bundle projects work like a charm

**Comment by angelos** [comment]
As a workaround, try restarting Eclipse.

I can confirm this seems only occur on Mars. Luna is fine.

**Comment by pkriens** [comment]
Angelos, can you check if the WorkspaceRepository in the repositories view is updated?

And what happens if you select the search bar and search? Do you see them then?

**Comment by bjhargrave** [comment]
@seanbright Here is a Windows related issue that perhaps you can look at?

**Comment by seanbright** [comment]
Angelos - if you click the 'Refresh' icon in the Repositories view:

![image](https://cloud.githubusercontent.com/assets/114601/11573423/516d35fc-99d4-11e5-8cd5-d85fed91fb54.png)

And then close and re-open the `.bndrun` file, does the new bundle show up?

**Comment by seanbright** [comment]
I would like to get an understanding of expected behavior. This is my experience right now with 3.1.0.DEV:

1. Launch eclipse, choosing a brand new empty workspace called `testing`
2. Switch to the Bndtools perspective
3. Right click in Package Explorer, New -> Bndtools OSGi Project
4. New Bnd OSGi Project Wizard
 1. Page 1 - Project name: `foo.a`
 2. Page 2 - Template: OSGi Standard Templates -> Component Development
 3. Page 3 - No changes, just click 'Finish'
5. Bnd editor opens for `foo.a`
6. Configuration Project Wizard appears, click next and finish accepting all defaults (Bundle-Hub Configuration) _(but see note below)_
7. Repositories View populates, if I expand the `Workspace testing` node I do see `foo.a` listed
8. Expand `foo.a` in Package Explorer and double click `launch.bndrun`
9. `foo.a` appears under the 'Browse Repos' panel
10. Right click in empty area of Package Explorer and repeat steps 3 thru 4.3, this time naming the new project `foo.b`

At this point, `foo.b` does __not__ appear under the `Workspace testing` node in the Repositories view, even if I collapse and expand it.

If I switch back to the `launch.bndrun` from `foo.a` that I left open, `foo.b` does __not__ appear in the 'Browse Repos' panel. However, if I type 'foo' in the search box of the 'Browse Repos' panel, both `foo.a` and `foo.b` are shown. `foo.b` is still not visible in the 'Repositories' view.

If I explicitly click the refresh button in the 'Repositories' view, `foo.b` appears under 'Workspace testing.'

So the question becomes - how does the current behavior deviate from the expected or desired behavior?

---

This could potentially be listed as a separate bug, but after step 6 above, you will have a new `cnf` project and the bnd editor for `foo.a` will be open from when it was created. If you switch to the 'Run' tab, there are no artifacts displayed under the 'Browse Repos' panel, and the editor appears to be in standalone mode (based on the icon shown next to 'Resolve/Run').

**Comment by seanbright** [comment]
@angelos What version of bndtools are you running?

**Comment by angelos** [comment]
Sorry, I didn't get around to answering all questions, but closing it seems a bit harsh :) Is this something that's up for an upcoming version?

**Comment by bjhargrave** [comment]
This bug is not closed.

**Comment by angelos** [comment]
My bad. I'll delete my comment, as it doesn't add to the conversation.

**Comment by angelos** [comment]
The BndTools version in my Eclipse is 3.0.0.REL-20150910-120816-g9a0d4f8 .

Refreshing and closing/reopening the editor doesn't help. Only thing that does it, is restarting Eclipse.

**Comment by seanbright** [comment]
@angelos What about refreshing the Repositories view:
![image](https://cloud.githubusercontent.com/assets/114601/11658106/f38f60ae-9d8e-11e5-8109-3c89fa070e8f.png)

**Comment by pkriens** [comment]
I've added a watcher on the Workspace's bnd files and reworked the refresh handling in the repositories view and the available bundles view. I think this was wrong, we were actually refreshing the plugins fom an event that indicated we just refreshed the repo. Surprised we did not get into a loop. So now the refresh action on the RepositoriesView is now done in the background. 

I decided to centralize the repositories viewer handling because we don't want the delay a repo can have because of network to show in the GUI. So viewers like the Available Bundles in the Run tab and the Repository Viewer. (I first had a utility class but then I iterated in the background over the repositories for each viewers, so that logic is now centralized.)

It feels a bit ugly, never got the hang of statics :-( Would be nice if @njbartlett  would take a look ...
