### ISSUE TITLE
Bug : When creating new Project Template, BndTools complains about incorrect -resourceonly

### ISSUE THREAD

**Issue by flangel** [bndtools/bndtools#1248]
3.1 RC2

1. Create new Bnd Project from Project Template template
2. open bnd.bnd
3. -resourceonly is missing ":" or shouldnt be there in the first place

**Comment by bjhargrave** [comment]
This should have already been fixed by https://github.com/bndtools/bndtools/commit/2eddb581f39ff4aa9a99a70c2a2d4cda31d6a872

But I also see this issue on my RC2 install. I initially suspected is a p2 problem since there are 2 versions of the org.bndtools.templates.template plugin in my plugins folder. But both versions of the plugin include the above mentioned fix.
