### ISSUE TITLE
bndrun: do not reorder -runbundles on resolve

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1367]
If there are -runbundles already in the bndrun file, then on resolve they are reordered, which is quite annoying. Please fix this.

Appending is ok, modifying in-place is ok (to change version range), removing is ok, but please do not change ordering.

Use-case: I've changed the order to make (for example) the log service start very early.

**Comment by paulf** [comment]
Although the opinions within the bndtools community indicate that start orders are not necessary I think  if the suggestion by Ferry were implemented bndtools would be a better product with better workflow.
Inmost cases problems with start order

**Comment by lostiniceland** [comment]
Since this bug affects me as well, I provided a PR. I usually setup Pax-Logging for my applications to start first in order to have a clear log-output during startup. Also Pax-CDI unfortunately requires a lot of changes to the start-order to function properly and it is quite annoying to change this after every resolve.

If the PR gets accepted, I would like to add some reordering-buttons to the runbundles list. In a perfect world each bundle should be able to start at any time and handle everything by itself...reality is different though
