### ISSUE TITLE
Provide support for -runblacklist

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1397]
The -runblacklist is an important feature. It would be nice if we could edit this list of black listed bundles with drag and drop.

**Comment by lostiniceland** [comment]
Initial Fix is working from Editor -> File, but in order to get the correct PropertyChangeEvent when editing the source BndEditModel needs to add _-runblacklist_ to its [KNOWN_PROPERTIES](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java#L71). Currently method _propertyChange_ on RunBlacklistsPart is never called due to that.
[This PR](https://github.com/bndtools/bnd/pull/1505) should fix this.

Regarding the UI, the Part has been placed between _Run Requires_ and _Run Bundles_
![runblacklist](https://cloud.githubusercontent.com/assets/1516116/16174220/3d3a2078-35b9-11e6-8633-0da31eefbacc.png)
Feedback welcome.

**Comment by pkriens** [comment]
@njbartlett Neil, can you take a look. I would really like to take this PR asap.

The window is becoming a bit cluttered but that is a problem that is already present. Maybe we should go  to 3 lists horizontal? Or do we need more tabs? I rarely ever touch the runtime properties, framework, and the order/selection of the repos. The edit debug cycle is really about repo content -> run reqs and now blacklist. However, I really would like to see the run bundles.

Anyway, regardless of these longer time concerns I think this is great.

**Comment by njbartlett** [comment]
Yes I agree a bit of housekeeping is in order. This panel is too cluttered even without the addition of another part.

I think that selection of the Framework and EE belongs on the same page as Requirements, because they are important inputs to the resolver. Repo selection and runtime properties can be moved to another tab.

**Comment by pkriens** [comment]
@njbartlett  But you're ok with this PR? Lets not the better stand in the way of the good ... :-)

**Comment by lostiniceland** [comment]
Another concern for this issue: this solution only takes the blacklist for the current run-file. Usually I add the blacklists to some global bnd-descriptor under _cnf/ext_. But this PR would help already, because advanced users can just copy the generated text to some global config. Until now I always have to copy the format from some existing blacklist and adjust (I tend to forgot this format).

Regarding the UI: I agree with Neil, having the Runtime on the Requirements, and moving the Properties to another page. The current section Runtime Properties is to small when having multiple entries and would benefit from more space.
If you guys create an issue for the housekeeping, I volunteer to work on it so you can focus on the core.

**Comment by njbartlett** [comment]
I haven't had time to review the PR. Of course I won't block it for the
housekeeping reasons I stated.
On 20 Jun 2016 09:01, "Peter Kriens" <notifications@github.com> wrote:

@njbartlett <https://github.com/njbartlett> But you're ok with this PR?
Lets not the better stand in the way of the good ... :-)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bndtools/bndtools/issues/1397#issuecomment-227074680>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAAY3o6ArbRhBL6ouJYV5Uyfuaqb6Lfzks5qNkjTgaJpZM4IwpO2>
.
