### ISSUE TITLE
Closing a Bndtool project do not remove it from the workspace repository

### ISSUE THREAD

**Issue by nport** [bndtools/bndtools#1436]
If in Eclipse a bndtool project is closed, the related bundle it still listed in the Workspace Repository.

**Comment by bjhargrave** [comment]
Closing a project in Eclipse does not remove the project from the Bnd Workspace. It is still on the file system. It is just the Eclipse view onto the project which is closed. So I don't see that closing the Eclipse project can affect the Bnd Workspace since Bnd does not know of Eclipse at all. Just the Bndtools Eclipse plugins, which use Bnd, know about Eclipse.

**Comment by nport** [comment]
In Eclipse PDE if you close a project you cannot use it anymore for debugging and it disappears from the plug-ins view. The same happens if you delete a project from the eclipse workspace, but without deleting it from the filesystem. I understand that gradle and bnd do not have any concept of project status and probably they only scan the workspace for *.bnd files, but from the point of view of a Eclpise PDE users, this behaviour may appear different from what it is expected.
