### ISSUE TITLE
testpath version not honored

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1462]
I have a repository that contains org.mockito.mockito-core version 2.0.91 and Central contains version 1.10.19.  Given:

-testpath: \
    ${junit}, \
    org.hamcrest; version=1.3,\
    org.mockito.mockito-core;version=1.10,\
    org.objenesis;version=1.0

bndtools will use version 2.0.91 instead of version 1.10.19.  If I move the dependency to -buildpath, the correct version 1.10.19 will be used.

**Comment by timothyjward** [comment]
Bryan,

What do you have defined in the ${junit} variable?

Tim

Sent from my iPhone

On 30 Jul 2016, at 02:46, Bryan Hunt <notifications@github.com<mailto:notifications@github.com>> wrote:


I have a repository that contains org.mockito.mockito-core version 2.0.91 and Central contains version 1.10.19. Given:

-testpath: \
${junit}, \
org.hamcrest; version=1.3,\
org.mockito.mockito-core;version=1.10,\
org.objenesis;version=1.0

bndtools will use version 2.0.91 instead of version 1.10.19. If I move the dependency to -buildpath, the correct version 1.10.19 will be used.

-

**Comment by BryanHunt** [comment]
# JUnit
junit: org.apache.servicemix.bundles.junit; version=4.12

**Comment by bjhargrave** [comment]
`-buildpath` uses `Strategy.LOWEST`: https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L507

`-testpath` uses `Strategy.HIGHEST`: https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L526

`-testpath` seems to have always uses `Strategy.HIGHEST`. I am not sure why it does not use `Strategy.LOWEST` like `-buildpath`.

So the fix here would be to use `Strategy.LOWEST` for `-testpath` if we agree.

**Comment by pkriens** [comment]
I think it makes a lot more sense to use HIGHEST. In general higher == better. The only reason we use LOWEST on -buildpath is to not create unnecessary dependencies in the generated bundles. The lowest strategy allows us to only require a low version meaning our bundle will be compatible with a larger number of runtimes. However, when we run bundles we generally want higher versions because it is likely that bugs are fixed.

So what about testing? Well, testing never leaves the development system so the problem of compatibility does not arise. However, the rule of the runtime where you want to leverage bug fixes does apply because you you will run that code in your JUnit tests. It would be very cumbersome to always manually updates your testpaths if you fixed HtmlUnit, JUnit, or mockito. All these products have always been highly compatible.

I therefore suggest to revert back to HIGHEST.

**Comment by bjhargrave** [comment]
Going back to HIGHEST means that the only safe way to use a jar in `-testpath` is with a version range. Saying `junit;version=3.8` is dangerous because when junit 4 appears in a repository, your build is broken. You then always need to say `junit;version=[3.8,4)` to always be safe.

**Comment by bjhargrave** [comment]
-testpath is both a compiler input (like -buildpath) and an execution input since the jars are used during test execution. For the compiler input side, LOWEST makes sense just like it does for -buildpath. For the test execution side, I can see that running HIGHEST makes sense, but doesn't that HIGHEST version need to be within the semantic version range of the same major version?

**Comment by pkriens** [comment]
-testpath defines both the compile time and runtime for the JUnit tests: compile == runtime. Therefore I fail to see what the benefit is to compile against LOWEST? It is not as if there is a compatibility issue with future unknown runtimes, something that is true for -buildpath?

We fatally picked higher than the specified version as the default but I am ok to limit this to the next major version by default. (You can already do this in bnd with `@1.2.3` which translates to `[1.2.3,2)`).

**Comment by BryanHunt** [comment]
What happens if someone releases a bundle that doesn't follow semantic versioning?  Does [1.2.3,1.2.3] guarantee to resolve agains version 1.2.3 and not 1.2.4?  BTW, that's what I assumed in the original issue, that version=1.2.3 would only resolve against 1.2.3.

**Comment by pkriens** [comment]
we follow the same rules as the OSGi ... So 1.2.3 is [1.2.3,∞). Yes, [1.2.3,1.2.3] can only handle that version though it does support different qualifiers.

**Comment by bjhargrave** [comment]
> -testpath defines both the compile time and runtime for the JUnit tests: compile == runtime. Therefore I fail to see what the benefit is to compile against LOWEST? It is not as if there is a compatibility issue with future unknown runtimes, something that is true for -buildpath?

The same predictability that people get on -buildpath. When they go version=1.2.3 to compile their code (test or not test) that they will not get version=inifinty.

> We fatally picked higher than the specified version as the default but I am ok to limit this to the next major version by default. (You can already do this in bnd with @1.2.3 which translates to [1.2.3,2)).

So do you mean to redefined HIGHEST strategy to stay within the major version range? In call cases, or just for -testpath? Perhaps we need a HIGHEST_IN_MAJOR strategy which can be applied to -testpath.

**Comment by pkriens** [comment]
I do not understand the predictability issue. Never been a problem and getting the latest version for my JUnit tests sounds very intuitive.

I think highest in major is probably a good default though the @1.2.3 syntax works for me as well. I am ok making HIGHEST limit to next major (though this of course fails in our JUnit example since 4.12 is perfectly compatible). Probably best leave it as it was.

**Comment by bjhargrave** [comment]
The @version syntax was unknown to me until this bug and I have used bnd for years... So I would guess it is not necessarily known or understood generally.

> Probably best leave it as it was.

Leave what as it was? How to we come to a resolution here?

**Comment by BryanHunt** [comment]
I'm ok reverting the change now that I understand that version=1.2.3 != version=[1.2.3,1.2.3].  Though to me that seems counter intuitive.
