### ISSUE TITLE
DeclarativeServicesAnnotationError if unbind method is missing

### ISSUE THREAD

**Issue by milendyankov** [bndtools/bndtools#1520]
I'm using BndTools 3.2.0 
If I add dynamic reference to a Component like this

```java
	@Reference (policy=ReferencePolicy.DYNAMIC)
	public void setMyOtherComponent(MyOtherComponent c) {
		// do something
	}
```
 and I don't have  `unsetMyOtherComponent`, building the workspace  fails with

```
Errors occurred during the build.
Errors running builder 'Bndtools Builder' on project 'simple.test.api'.
Build Error!
aQute.bnd.component.error.DeclarativeServicesAnnotationError cannot be cast to aQute.bnd.component.error.DeclarativeServicesAnnotationError
Build Error!
aQute.bnd.component.error.DeclarativeServicesAnnotationError cannot be cast to aQute.bnd.component.error.DeclarativeServicesAnnotationError
```
Same thing happens if `unbind` points to nonexistent method.

I understand this deserves a warning (and IIRC this is what BndTools used to give me in the past) but it definitely shouldn't fail IMHO.

**Comment by timothyjward** [comment]
> I understand this deserves a warning (and IIRC this is what BndTools used to give me in the past) but it definitely shouldn't fail IMHO.

This is, has been, and should be an error in bnd/Bndtools. A dynamic reference can and will be unbound from a running component. A failure to supply the unbind method indicates a misunderstanding of this lifecycle behaviour - if you don't have an unbind method for a dynamic reference (when using a bind method) then the component is definitely broken as there is no way to "remove" the invalid service when it is unregistered. 

If you really want to avoid this failure cratering your build then this can be achieved using bnd instructions, but I would strongly recommend that you fix the broken component.

See http://bnd.bndtools.org/instructions/fixupmessages.html if you really want to keep going with the component as is.

**Comment by milendyankov** [comment]
I will not argue on whether this should be warning or error _(although I'm tempted to install some old bndtools version to double check, because I'm pretty sure it used to be warning)_.
 
What I would argue though, is that very few people (if anyone at all) will know that 
```
aQute.bnd.component.error.DeclarativeServicesAnnotationError cannot be cast to aQute.bnd.component.error.DeclarativeServicesAnnotationError
```
actually means "there is missing unbind method". And I assume it may also mean lots of other things!

**Comment by milendyankov** [comment]
Also @timothyjward would you please explain, what is the difference between not providing an unbind method and providing one that does nothing? And why according to bndtools first one causes the whole build to fail and the other one does not?

**Comment by timothyjward** [comment]
> Also @timothyjward would you please explain, what is the difference between not providing an unbind method and providing one that does nothing? And why according to bndtools first one causes the whole build to fail and the other one does not?

From a programming perspective it is likely that both of these things are equally wrong, however there's only so smart that a software tool can be before you hit the halting problem...

In this case we know that when using setter methods (rather than field injection) for a `dynamic` reference you *must* handle the case where the service is unbound. Bnd holds this knowledge, and so if you don't provide an `unset`/`unbind`/`remove` method then it records a failure in the annotation processor. If you *do* add an unbind method then Bnd *does not* attempt to validate the correctness of the method implementation as this would, in the general case, be impossible.

The idea behind this is simple - with the logic as is Bnd will catch common problems, such as when you:

* Forget the unbind method completely
* Write an unbind method with the wrong signature (useful when refactoring)
* Typo the unbind method name

What Bnd won't do is attempt to validate the thread safety (or reference safety) of your code. An empty unbind method is almost certainly wrong, except in the case where the bind method doesn't hold on to the referenced service. This is a vanishingly small case, and even then it is highly unlikely that you don't want to perform some additional work when the service is unbound. If it turns out that this really is the case, then in all likelihood you should not be using Declarative Services to manage the reference, but using a lower level construct like a ServiceTracker instead.

I would be very interested to know what this component is doing which you believe doesn't need to perform any work on unbind...

**Comment by timothyjward** [comment]
> What I would argue though, is that very few people (if anyone at all) will know that
>
>    aQute.bnd.component.error.DeclarativeServicesAnnotationError cannot be cast to aQute.bnd.component.error.DeclarativeServicesAnnotationError
>
> actually means "there is missing unbind method". And I assume it may also mean lots of other things!

I agree that this is true, however I'm using 3.2.0.REL and the message I see is:

    In component class xxx.yyy.zzz.MyComponent, reference Provider is dynamic but has no 
 unbind method.

At a guess your Eclipse installation has multiple versions of Bndtools knocking around inside it - this can happen due to the horror that is p2 and the Eclipse marketplace installer. I would suggest that uninstalling Bndtools, cleaning out any residual Bndtools bundles from Eclipse's plugins, then re-installing Bndtools would be a good idea.

**Comment by milendyankov** [comment]
No, I think you wrongly understood my intention. I don't look into purposely doing this. This happened to me because I forgot the add the unbind method. The problem is I made this change (static to dynamic) together with a bunch of other changes and the on saving the file the whole thing "exploded". It took me couple of hours to figure out a missing unbind method was causing this.

**Comment by timothyjward** [comment]
> No, I think you wrongly understood my intention. I don't look into purposely doing this. This happened to me because I forgot the add the unbind method. The problem is I made this change (static to dynamic) together with a bunch of other changes and the on saving the file the whole thing "exploded". It took me couple of hours to figure out a missing unbind method was causing this.

In which case it sounds like the error is doing its job correctly - i.e. telling you that it's not sufficient to add policy=DYNAMIC, but that you also need an unbind method.

The ClassCastException will have made life harder, but that looks like a problem with your Eclipse Plugins affecting your Bndtools installation. At a guess you've tried out a snapshot build at some point and p2 has failed to clean it all up?

**Comment by milendyankov** [comment]
Hmm, you may be right. I upgraded to bndtool to 3.2.0.REL not so long ago. Don't recall any issues but let me try what you suggest and report back. Thanks for your help.

**Comment by timothyjward** [comment]
These are all the bndtools plugins I have installed for 3.2.0.REL:

<img width="750" alt="screen shot 2016-09-05 at 12 05 51" src="https://cloud.githubusercontent.com/assets/3882104/18246086/247389ea-7361-11e6-91ab-01a29557ffe4.png">

**Comment by milendyankov** [comment]
You are right! 

The problem could be related to Liferay IDE which installs also bndtools 3.1.0 bundles. In fact I couldn't uninstall bndtools without uninstalling Liferay IDE. 

So having installed bndtools only, I am getting proper error message. Even installing Liferay IDE **after** bndtools 3.2.0.REL works OK. 

I'm guessing something went wrong when bndtools 3.2.0.REL was installed after Liferay IDE 3.0.0. Perhaps it couldn't upgrade properly because there was not bndtools 3.1.0 per se, but just bundles provides by other plugin? I don't know nearly enough about Eclipse's plugin/feature mechanics to tell if this is the case though? If so though, what do you think needs to be done to ensure both works together regardless of the order in which they are installed?

**Comment by milendyankov** [comment]
I keep forgeting github has mentins.
@gamerson, you may want to know about this

**Comment by gamerson** [comment]
thanks @milendyankov we will take a look.  it does seem that p2 is causing some upgrade friction here.  We can take a look.
