### ISSUE TITLE
Built-in template repository produces invalid projects

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#1549]
I worked with an inexperienced Bndtools user today who was experiencing difficulty. On opening a fresh workspace, he first created a new Bnd project. This brought up the template selection wizard page, with content derived from bundle-hub. Next he created the workspace/cnf.

This led to projects with invalid dependencies. The templates in the built-in repo have no idea what kind of workspace and repos will be created, so they cannot declare dependencies that are guaranteed to be valid. However if the workspace is created first then the workspace repos can contribute project templates, and those templates can be kept consistent with the available resources in the repos.

I present the following possible solutions for discussion:
1. Prevent the creation of bnd projects using the wizard until after the workspace has been created. The user would have to be clearly guided to use the workspace wizard, for example it could appear as a shortcut on the Eclipse Welcome page.
2. Strip the content of the built-in repo to contain only simple projects without dependencies. (Also I suggest adding a template for a Maven project using the bnd-maven-plugin). Note that changes to bundle-hub are decoupled from the Bnd(tools) release cycle, so this can be done before 3.4.

**Comment by timothyjward** [comment]
I've definitely seen people confused because they create a project which is useless without a workspace. It doesn't help that many of these people are also confused about the need for a workspace and what it does.

Given that we now have both "workspace" and "non-workspace" projects it would be ideal if the UI could provide some help when selecting a template.

* Greying out workspace templates until a workspace exists
* Clearly separating workspace and non workspace templates
* Reducing the number of templates presented based on information about the workspace (e.g. if I use an enRoute workspace then preferentially show the enRoute templates). This would need to be overridable (possibly a "more..." button).

We've done a great job making bndtools more flexible and improving its integration with other tools, but I do worry that we have lost focus on simplicity. Perhaps 3.4 would be a good opportunity to take stock, and to streamline the templates and processes for new starters?

**Comment by njbartlett** [comment]
To clarify I'm talking about project templates, i.e. templates that generate projects. The "workspace templates" (that generate workspaces) are already completely separated. There are only the following sources of project templates:

1. Bundles in the workspace and the repositories configured by the workspace. Prior to creation of the workspace, this returns an empty list.
2. Bundles in the template repository that is configured in Eclipse Preferences (Prefs > Bndtools > Repositories).
3. A singleton "empty" template.

Additionally the New Project wizard always contains the EnRoute Wizard because it is provided via an Eclipse Extension, for legacy reasons.

I think that number 2 needs to be removed. As Tim notes, the templates there generate projects that don't work. Also the EnRoute Wizard needs to be migrated to use the template system.

On your third point Tim (reduce number of templates and base them on the workspace)... I believe this is covered by number 1. Since the templates come from the workspace, they can be customized for that workspace. For example the EnRoute templates would be in the EnRoute workspace and so use all of the EnRoute dependencies that are in the repos.
