### ISSUE TITLE
bndtools 3.4.0.REL doesn't understand the bndrun syntax 'a.b;version[1,1]'

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1754]
bndtools 3.4.0.REL doesn't understand the runbundles syntax

```
nl.pelagic.service.log.syslog;version='[3.0.2,3.0.2]',\
...
```

On launch (of its bndrun) I get:
```
Status ERROR: bndtools.core code=0
Cannot find /error/nl.pelagic.service.log.syslog;version=[3.0.2,3.0.2]
Not found in
[bnd-cache [/home/ferry/vcs/nbs/ahrplefe/cnf/cache/3.4.0/bnd-cache r/w=false],
Local,
Release,
ReleaseCI,
Build [/home/ferry/vcs/nbs/ahrplefe/cnf/buildrepo r/w=true],
Pelagic OSGi Components [/home/ferry/vcs/nbs/ahrplefe/cnf/cache/PelagicOSGiComponents r/w=false],
OLSR [/home/ferry/vcs/nbs/ahrplefe/cnf/cache/OLSR r/w=false],
MavenBndRepository [localRepo=/home/ferry/.m2/repository, storage=Maven Central - Local, inited=true],
MavenBndRepository [localRepo=/home/ferry/.m2/repository, storage=Maven Central - Build, inited=true],
Build - Workspace [/home/ferry/vcs/nbs/ahrplefe/cnf/gradle/dependencies r/w=true],
MavenBndRepository [localRepo=/home/ferry/.m2/repository, storage=Maven Central - Workspace, inited=true]] null
```

When I change it to:
```
nl.pelagic.service.log.syslog;version='[3.0.2,3.0.3)',\
...
```
then it works correctly.

On top of that, the error seems to indicate that bndtools does not respect the configured runrepos I have:
```
-runrepos:  \
	Workspace,\
	Local
```

because the error mentions all of my repos.

**Comment by bjhargrave** [comment]
Looking at the bnd file for the bundle `nl.pelagic.service.log.syslog`:

https://github.com/fhuberts/osgiComponents/blob/6510040858cac482e98b009a7d603bf29ea9f3b1/nl.pelagic.service.log.syslog/bnd.bnd#L2

your Bundle-Version has a qualifier of the timestamp. So `version='[3.0.2,3.0.2]'` would never match `3.0.2.xxx` where xxx is a timestamp. This is why `version='[3.0.2,3.0.3)'` works. Because it allows for a qualifier to be present. `version='[3.0.2,3.0.2]'` can only match `3.0.2` without any qualifier.

Currently, `-runrepos` only applies to the repos used when resolving. See

https://github.com/bndtools/bnd/blob/f1aeacda844d28ea717d24c8291e0c023afe468f/biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java#L355

So it does not apply to locating bundles listed in `-runbundles`. The description for `-runrepos` on http://bnd.bndtools.org/chapters/825-instructions-ref.html says:

`Order and select the repository for resolving against. The default order is all repositories in their plugin creation order.`

I am not saying this is the way it should be. It is just the way it currently is. It would be a behavioral change to apply `-runrepos` to other contexts.

**Comment by fhuberts** [comment]
On 25/08/17 16:32, BJ Hargrave wrote:
> Looking at the bnd file for the bundle |nl.pelagic.service.log.syslog|:
> 
> https://github.com/fhuberts/osgiComponents/blob/6510040858cac482e98b009a7d603bf29ea9f3b1/nl.pelagic.service.log.syslog/bnd.bnd#L2
> 
> your Bundle-Version has a qualifier of the timestamp. So 
> |version='[3.0.2,3.0.2]'| would never match |3.0.2.xxx| where xxx is a 
> timestamp. This is why |version='[3.0.2,3.0.3)'| works. Because it 
> allows for a qualifier to be present. |version='[3.0.2,3.0.2]'| can only 
> match |3.0.2| without any qualifier.

I was interpreting things as 3.0.2.x is still 3.0.2.
I can see your point and I was just surprised.
I don't really feel strong about this.


> 
> Currently, |-runrepos| only applies to the repos used when resolving. See
> 
> https://github.com/bndtools/bnd/blob/f1aeacda844d28ea717d24c8291e0c023afe468f/biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java#L355
> 
> So it does not apply to locating bundles listed in |-runbundles|. The 
> description for |-runrepos| on 
> http://bnd.bndtools.org/chapters/825-instructions-ref.html says:
> 
> |Order and select the repository for resolving against. The default 
> order is all repositories in their plugin creation order.|
> 
> I am not saying this is the way it should be. It is just the way it 
> currently is. It would be a behavioral change to apply |-runrepos| to 
> other contexts.

I hope that you're willing to change it because IMHO runbundles is 
runtime information and runrepos determines which repos are allowed for 
runtime information. Not adhering to that makes things inconsistent.

**Comment by bjhargrave** [comment]
> I was interpreting things as 3.0.2.x is still 3.0.2.
> I can see your point and I was just surprised.
> I don't really feel strong about this.

This is just how OSGi versions work.



> I hope that you're willing to change it because IMHO runbundles is runtime information and runrepos determines which repos are allowed for runtime information. Not adhering to that makes things inconsistent.

Well this is a feature request, so please open an issue in the bnd repo. The bndtools repo is not the proper place.
