### ISSUE TITLE
Dependency on parent project when using nested projects

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bndtools#1847]
1) Create new bnd workspace in folder `test`
2) Create bundle project `test.bundle1`, add a class
3) Create bundle project `test.bundle2`, add a class
4) Put `test.bundle2` on `test.bundle1`'s build path

Looks fine, project `test.bundle1`'s `Bnd Bundle Path` contains `test.bundle2.jar` and project `test.bundle2
`, everything is built.

5) Now create an Eclipse project in `test`, the parent folder of `cnf`, `test.bundle1` and `test.bundle2`. (Why? Because it allows you to easily see, edit and RCS-manage the `README.md`, the `build.gradle` etc. in Eclipse.)
6) Clean and wait for build to finish (or use some other way to trigger a build).

Looks bad now: project `test.bundle1`'s `Bnd Bundle Path` contains project `test` (the newly created project) instead of project `test.bundle2` (and still `test.bundle2.jar`, which is okay). And project `test.bundle1` isn't built anymore, error message: "Project 'test.bundle1' is missing required Java project: 'test'"

**Comment by bjhargrave** [comment]
You lost me at step 5.

In my Eclipse workspace for Bnd, I created a `root` project which I use to hold links to the files in the root of the git repo.

<img width="226" alt="image" src="https://user-images.githubusercontent.com/277682/37246082-aa125b14-2470-11e8-8d13-7ae0c10c7923.png">

In the `root` project, I did New -> File and, under Advanced, chose Link to file in the file system. I also created a GIT_ROOT variable to use to point to the root of the git repo.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/277682/37246117-2b4d315e-2471-11e8-9735-8a1ceac5dee9.png">

This works fine for what you want and his no effect on the build.

Finally, it is important to note that the Eclipse workspace for Bnd and the git repo for Bnd are in complete separate folders. This means the `root` folder I created lives in the folder of the Eclipse workspace for Bnd and _not_ in the folder of the git repo for Bnd. I think your mistake is that you put your Bnd projects in the Eclipse workspace folder rather than in a separate folder from the Eclipse workspace.

**Comment by mnlipp** [comment]
Using links seems a bit complicated to me. Here's my "straightforward" project structure:

![grafik](https://user-images.githubusercontent.com/1446020/37247999-53a410a0-24c6-11e8-856c-6393344f9a1e.png)

Of course, you see more in the Navigator:

![grafik](https://user-images.githubusercontent.com/1446020/37247983-f2cdca1e-24c5-11e8-8703-45ee6eed2eb6.png)

The top-level `test/.project` was introduced in step 5 with "File/New/General/Project". 

I wasn't aware that I could upload files here. So here's the complete project:  [test.zip](https://github.com/bndtools/bndtools/files/1799917/test.zip). Import it in Eclipse (including subprojects) and you should see the red exclamation mark as shown in the picture above (make sure to switch to hierarchical project presentation in the project explorer). Remove the `test/.project` (undoes step 5), delete the project in Eclipse (not its contents, of course) and the problem goes away. Re-create the general project in folder `test`, trigger a rebuild and it reappears.

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? I still don't see the full picture of what I think you are talking about.

**Comment by mnlipp** [comment]
Okay, here your are: [mnlipp/test](https://github.com/mnlipp/test).

As before, make sure to include the nested projects on import.
![grafik](https://user-images.githubusercontent.com/1446020/37252503-10948522-2522-11e8-837a-d570a93c3398.png)

And switch to the hierarchical view in the project explorer.
![grafik](https://user-images.githubusercontent.com/1446020/37252790-f685a638-2527-11e8-95d9-f2634f5557f5.png)

As you can see, this is the perfect view for working with the bnd workspace. It doesn't require any links and still you have all files in direct access. Well, "perfect" except for the bug, of course.

BTW, I just found that it is sufficient to delete the top project `test` (not deleting the contents, of course) from Eclipse to get rid of the problem, no need to delete `test/.project`. 

So, delete project `test`: problem goes away. Re-import `test` and trigger rebuild: problem's back. I wouldn't call this a work-around, though...

**Comment by bjhargrave** [comment]
Thanks for the repo. I was able to reproduce the issue.

The problem is caused by the fact that the generated jar for `test.bundle2` (`test.bundle2/generated/test.bundle2.jar`) is visible in the Eclipse workspace twice. Once under the `test` project: `/test/test.bundle2/generated/test.bundle2.jar`, and once under the `test.bundle2` project: `/test.bundle2/generated/test.bundle2.jar`.

So when Bndtools is trying to compute the classpath container for the `test.bundle1` project, it must map the `test.bundle2/generated/test.bundle2.jar` file on the file system (`/Users/hargrave/git/tmp/mlipptest/test.bundle2/generated/test.bundle2.jar` in my case) to the `IPath` of resource in the Eclipse workspace. But there are two choices and the code chooses one which, in this case, is the resource on the `test` project. 

https://github.com/bndtools/bndtools/blob/9647bcdc4f1fce45ce16fa31567bb5839e950c3b/bndtools.core/src/bndtools/central/Central.java#L399-L407

The `IPath` is then mapped to the `IProject` holding the resource which can be either the `test` project or the `test.bundle2` project.

https://github.com/bndtools/bndtools/blob/9647bcdc4f1fce45ce16fa31567bb5839e950c3b/bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java#L329-L332

There is no easy way for the code to know, when you have constructed an Eclipse workspace where the same file on the file system is mapped into multiple Eclipse projects, which `IPath` and thus which `IProject` to use as the "owner" of the resource.

So in your example repo, the `test` project is chosen as the Eclipse project for the `test.bundle2/generated/test.bundle2.jar` resource which is wrong since the `test` project is not a Java nature project which upsets JDT resulting in the errors.

**Comment by mnlipp** [comment]
> There is no easy way for the code to know, when you have constructed an Eclipse workspace where the same file on the file system is mapped into multiple Eclipse projects, which IPath and thus which IProject to use as the "owner" of the resource.

Wouldn't the fact that the bnd workspace must be flat serve as an easy criterion? Of the two candidates `/test/test.bundle2/generated/test.bundle2.jar` and `/test.bundle2/generated/test.bundle2.jar` only one is a sibling of (has the same parent path as) `/test/test.bundle1/`.

**Comment by bjhargrave** [comment]
> only one is a sibling of (has the same parent path as) /test/test.bundle1/.

But that path in unknown at the time of the selection. It is also the wrong path for project `test.bundle`. I assume you meant `/test.bundle`.

I made a PR which selects the path with the smallest segment count which should produce the desired results since `/test.bundle2/generated/test.bundle2.jar` has a lower segment count than `/test/test.bundle2/generated/test.bundle2.jar`.

**Comment by mnlipp** [comment]
Just in case someone comes across this: you can work around the problem by making the top-level eclipse project a Java project (there is no Java in it, but this doesn't matter). Just don't use `project` [in version references](https://github.com/bndtools/bnd/wiki/Buildpath-Versions). (`snapshot` is preferable anyway because it uses the generated bundle and thus ensures a better compatibility with an eventually released version.)

**Comment by bjhargrave** [comment]
> Just in case someone comes across this

Also, you can avoid this issue if the top-level eclipse project's name is chosen to not be a prefix of any other projects name.

**Comment by bjhargrave** [comment]
> snapshot is preferable

Actually, I would recommend `version=latest` to refer to other generated jar of another project.

**Comment by mnlipp** [comment]
> Also, you can avoid this issue if the top-level eclipse project's name is chosen to not be a prefix of any other projects name.

I have doubts about that. The "real" project where the issue hit me uses `ad-hoc-polling` as top-level
name and sub projects are named `de.mnl.ahp.*`.
