### ISSUE TITLE
BndContainerInitializer doesn't handle embedded jars

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bndtools#1871]
I was using a 3rd-party bundle (specifically, `org.apache.ant` from the Orbit Oxygen repository) that contains jars that are embedded and referenced via a `Bundle-ClassPath` directive. I was getting persistent compilation errors about an imported package missing, even though it was in the Export-Package list for the main bundle.

Eventually, after comparing with the same project in PDE, I suspected that this was because Bndtools wasn't including the embedded jars on the build path. (PDE, on the other hand, lists the embedded jars in the Plugin Dependencies container as subdirectories of the main bundle jar.)

I know that in the Bnd documentation it frowns upon creating bundles in this way, and I tend to agree (I wouldn't create my own bundle this way). But it is in the spec, and there are bundles out there written this way, so would be nice if Bndtools could handle it.

In my case, a workaround was to directly referencreinclude the embedded Jar in question from Maven Central instead of using the bundle - this at least gets it to build. The problem with this is it circumvents the package export declarations.

**Comment by bjhargrave** [comment]
This is a dup of #1022 and #1198.

Bundle-ClassPath is a tool for making types available at runtime but not at compile-time. No compiler understands Bundle-ClassPath and we need to have fidelity with the other build environments (maven, gradle). So adding support to Bndtools/Eclipse for Bundle-ClassPath means that those projects would not compile in maven or gradle. Build fidelity is a key attribute we must preserve.

**Comment by kriegfrj** [comment]
> This is a dup of #1022 and #1198.

Sorry for the dup, I searched before reporting but I must have only searched open issues. 

Are there any examples of how one goes about using the `expand-bcp` parameter? Looks like it should do the trick in theory, but I'm having some issues with the practice.

My two bits about the rest of your comments:

>Bundle-ClassPath is a tool for making types available at runtime but not at compile-time. No compiler understands Bundle-ClassPath and we need to have fidelity with the other build environments (maven, gradle). So adding support to Bndtools/Eclipse for Bundle-ClassPath means that those projects would not compile in maven or gradle. Build fidelity is a key attribute we must preserve.

* Every bundle has a default Bundle-ClassPath of ".". From the OSGi framework perspective, there's nothing special about ".", and other Bundle-ClassPath entries are treated the same as ".".
* It is true that no compiler understands Bundle-ClassPath. But then, it is also true that no compiler really understands dependency management, period. That is why we have tools like Maven, Gradle, PDE and Bnd that manage the dependencies and then ensure that compiler has the correct ones. 
* There's more than one type of build fidelity. You're talking about fidelity between build systems, which is undoubtedly useful, but fidelity between the build and runtime environments is also useful. As you no doubt appreciate, the development cycle is more efficient when errors are caught at build time than at run time (that's why we bother with the overheads of a strongly typed language like Java). The more closely the build-time dependency resolution matches the run time dependency resolution, the less chance that you will hit errors for the first time at runtime. Given that the OSGi runtime spec supports Bundle-ClassPath, ideally OSGi-aware build tools would also support it. It is extremely useful, for example, that Bndtools will tell you almost immediately if you try and import a class from a bundle's private package - something that a non-OSGi-aware build tool wouldn't/couldn't do.
* It seems it would be possible to get Maven and Gradle to support Bundle-ClassPath with the correct Bnd plugins if Bnd itself supported it. Then you could have your cake and eat it.
* More generally, I feel that a decision as to whether build system fidelity is important should be left to the Bnd/Bndtools user rather than being forced on them. If I'm not using Maven or Gradle, then that sort of fidelity is not important to me, or perhaps I would be willing to sacrifice that part of the fidelity for something else that is more important. There is already precedent for this in Bndtools - for example, Bndtools will warn rather than fail if Eclipse's src/test/output directories don't match Bnd's; similarly if the JRE version doesn't match.
* I realise that all of this is probably not trivial.

**Comment by bjhargrave** [comment]
> Are there any examples of how one goes about using the expand-bcp parameter?

You can `git grep expand-bcp` to see there is one test case testing it. But, as near as I can tell, the code which handles `expand-bcp` is never called by Bndtools or the gradle plugin for workspace model builds when setting up the classpath for compilation. Also, the code supporting `expand-bcp` just assumes it can write in the location of the bundle which may not be possible and also may be a bad idea.

> It seems it would be possible to get Maven and Gradle to support Bundle-ClassPath with the correct Bnd plugins if Bnd itself supported it. Then you could have your cake and eat it.

This may be true for the Bnd Gradle plugin for workspace model builds since that plugin will set the classpath for the compiler. But for non-workspace model gradle builds and maven builds, the compiler classpath is set in the normal gradle or maven way and Bnd code is not involved and cannot do anything regarding BCP.

So any support for BCP would be limited to Bnd workspace model builds where Bnd/Bndtools are in charge of the build setup and can configure the compiler classpath. For non-workspace model builds, we are not involved in setting up the compiler classpath and thus cannot do anything.

As you see, the Bnd maintainers are not driving any change to support BCP during compilation. If you are motivated, then you should make a design proposal we can review and comment on (before you embark in a direction we may object to). But I will say that build fidelity between the IDE and the command line build is important to me.
