### ISSUE TITLE
NullPointerException after adding exported package

### ISSUE THREAD

**Issue by santiagozky** [bndtools/bndtools#781]
While trying Bndtools for the first time I got the following error:
"Error finding source package for exported 1packages."

This happened in a multi module maven project. I added the bndtools nature to one of the modules, the cnf project was created successfully.
Afterwards I added a new exported package and the error appeared:
"Error finding source package for exported 1packages."
   java.lang.NullPointerException.

Afterwards, the package info dialog does not appear.

setup:
Eclipse: Kepler Release Build id: 20130614-0229
Bndtools:   2.2.2.REL-20131018-171114

**Comment by mnlipp** [comment]
The problem is still there. I'm just trying to walk through the tutorial. In order to keep things clean, I've created a top-level project OSGi-Test and put everything below it. Version is 3.1.0.REL-20151218-090315-gffa01d9 (what a number, and not even copyable!).

[OSGi-Test.zip](https://github.com/bndtools/bndtools/files/82934/OSGi-Test.zip)

Quite frustrating to run into such a problem when you do your first steps...

**Comment by bjhargrave** [comment]
I suggest opening a new issue since this one is rather old and long since closed.

**Comment by unitydynamics** [comment]
Still an issue for me here as a beginner in 2016

**Comment by pkriens** [comment]
I do not expect to be the same issue . So can open a new issue and provide information so we can diagnose this?
